# Generated by Django 4.0.5 on 2022-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('coreo', models.CharField(max_length=40, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Numero')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
            ],
        ),
    ]
