# Generated by Django 4.0.3 on 2022-06-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('coreo', models.CharField(max_length=40, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Numero')),
                ('producto', models.CharField(max_length=30, verbose_name='Producto')),
                ('cantidad', models.CharField(max_length=3, verbose_name='Cantidad')),
            ],
        ),
    ]
